/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const BloodGroup = IDL.Variant({
  'ANeg' : IDL.Null,
  'APos' : IDL.Null,
  'BNeg' : IDL.Null,
  'BPos' : IDL.Null,
  'ONeg' : IDL.Null,
  'OPos' : IDL.Null,
  'ABNeg' : IDL.Null,
  'ABPos' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Donor = IDL.Record({
  'id' : UserId,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'bloodGroup' : BloodGroup,
  'phone' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const DonorInput = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'bloodGroup' : BloodGroup,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMyProfile' : IDL.Func([], [IDL.Opt(Donor)], ['query']),
  'registerDonor' : IDL.Func(
      [DonorInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchDonors' : IDL.Func([BloodGroup], [IDL.Vec(Donor)], ['query']),
  'updateDonor' : IDL.Func(
      [DonorInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const BloodGroup = IDL.Variant({
    'ANeg' : IDL.Null,
    'APos' : IDL.Null,
    'BNeg' : IDL.Null,
    'BPos' : IDL.Null,
    'ONeg' : IDL.Null,
    'OPos' : IDL.Null,
    'ABNeg' : IDL.Null,
    'ABPos' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Donor = IDL.Record({
    'id' : UserId,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'bloodGroup' : BloodGroup,
    'phone' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const DonorInput = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'bloodGroup' : BloodGroup,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getMyProfile' : IDL.Func([], [IDL.Opt(Donor)], ['query']),
    'registerDonor' : IDL.Func(
        [DonorInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchDonors' : IDL.Func([BloodGroup], [IDL.Vec(Donor)], ['query']),
    'updateDonor' : IDL.Func(
        [DonorInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };