/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'ANeg' : null } |
  { 'APos' : null } |
  { 'BNeg' : null } |
  { 'BPos' : null } |
  { 'ONeg' : null } |
  { 'OPos' : null } |
  { 'ABNeg' : null } |
  { 'ABPos' : null };
export interface Donor {
  'id' : UserId,
  'age' : bigint,
  'name' : string,
  'bloodGroup' : BloodGroup,
  'phone' : string,
  'registeredAt' : Timestamp,
}
export interface DonorInput {
  'age' : bigint,
  'name' : string,
  'bloodGroup' : BloodGroup,
  'phone' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'getMyProfile' : ActorMethod<[], [] | [Donor]>,
  'registerDonor' : ActorMethod<
    [DonorInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchDonors' : ActorMethod<[BloodGroup], Array<Donor>>,
  'updateDonor' : ActorMethod<
    [DonorInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];