/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface Donor {
    id: UserId;
    age: bigint;
    name: string;
    bloodGroup: BloodGroup;
    phone: string;
    registeredAt: Timestamp;
}
export interface DonorInput {
    age: bigint;
    name: string;
    bloodGroup: BloodGroup;
    phone: string;
}
export enum BloodGroup {
    ANeg = "ANeg",
    APos = "APos",
    BNeg = "BNeg",
    BPos = "BPos",
    ONeg = "ONeg",
    OPos = "OPos",
    ABNeg = "ABNeg",
    ABPos = "ABPos"
}
export interface backendInterface {
    getMyProfile(): Promise<Donor | null>;
    registerDonor(input: DonorInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchDonors(bloodGroup: BloodGroup): Promise<Array<Donor>>;
    updateDonor(input: DonorInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { BloodGroup as _BloodGroup, Donor as _Donor, DonorInput as _DonorInput, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMyProfile(): Promise<Donor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerDonor(arg0: DonorInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDonor(to_candid_DonorInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDonor(to_candid_DonorInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchDonors(arg0: BloodGroup): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonors(to_candid_BloodGroup_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonors(to_candid_BloodGroup_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonor(arg0: DonorInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonor(to_candid_DonorInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonor(to_candid_DonorInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BloodGroup_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donor]): Donor | null {
    return value.length === 0 ? null : from_candid_Donor_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    age: bigint;
    name: string;
    bloodGroup: _BloodGroup;
    phone: string;
    registeredAt: _Timestamp;
}): {
    id: UserId;
    age: bigint;
    name: string;
    bloodGroup: BloodGroup;
    phone: string;
    registeredAt: Timestamp;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        bloodGroup: from_candid_BloodGroup_n4(_uploadFile, _downloadFile, value.bloodGroup),
        phone: value.phone,
        registeredAt: value.registeredAt
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ANeg: null;
} | {
    APos: null;
} | {
    BNeg: null;
} | {
    BPos: null;
} | {
    ONeg: null;
} | {
    OPos: null;
} | {
    ABNeg: null;
} | {
    ABPos: null;
}): BloodGroup {
    return "ANeg" in value ? BloodGroup.ANeg : "APos" in value ? BloodGroup.APos : "BNeg" in value ? BloodGroup.BNeg : "BPos" in value ? BloodGroup.BPos : "ONeg" in value ? BloodGroup.ONeg : "OPos" in value ? BloodGroup.OPos : "ABNeg" in value ? BloodGroup.ABNeg : "ABPos" in value ? BloodGroup.ABPos : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n2(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_DonorInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorInput): _DonorInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    bloodGroup: BloodGroup;
    phone: string;
}): {
    age: bigint;
    name: string;
    bloodGroup: _BloodGroup;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        bloodGroup: to_candid_BloodGroup_n8(_uploadFile, _downloadFile, value.bloodGroup),
        phone: value.phone
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    ANeg: null;
} | {
    APos: null;
} | {
    BNeg: null;
} | {
    BPos: null;
} | {
    ONeg: null;
} | {
    OPos: null;
} | {
    ABNeg: null;
} | {
    ABPos: null;
} {
    return value == BloodGroup.ANeg ? {
        ANeg: null
    } : value == BloodGroup.APos ? {
        APos: null
    } : value == BloodGroup.BNeg ? {
        BNeg: null
    } : value == BloodGroup.BPos ? {
        BPos: null
    } : value == BloodGroup.ONeg ? {
        ONeg: null
    } : value == BloodGroup.OPos ? {
        OPos: null
    } : value == BloodGroup.ABNeg ? {
        ABNeg: null
    } : value == BloodGroup.ABPos ? {
        ABPos: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
